[package]
name = "rust-todo-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
bytes = "1.7.1"
prost = "0.13.1"
prost-types = "0.13.1"
serde = { version = "1.0.204", features = ["derive"] }
serde_json = "1.0.122"

[build-dependencies]
prost-build = "0.13.1"